name: Citadel - Main CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r all_requirements.txt
          pip install black flake8 pytest
      - name: Run linting and formatting checks
        run: |
          black --check .
          flake8 .
      - name: Run tests
        run: pytest

  build-and-scan-services:
    name: Build & Scan Docker Images
    runs-on: ubuntu-latest
    needs: lint-and-test
    strategy:
      matrix:
        service:
          - api_gateway
          - vector_search
          - knowledge_graph
          - causal_inference
          - time_series
          - multi_modal
          - hierarchical_classification
          - rule_engine
          - shell_command
          - orchestrator
          - web_service
          - nl_agent
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb
      - name: Build Docker image
        run: |
          docker build -t citadel/${{ matrix.service }}:latest -f ./${{ matrix.service }}/Dockerfile .
      - name: Scan image with Trivy for high/critical vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL citadel/${{ matrix.service }}:latest
